# copywarfile.yml
---
- hosts: all 
  become: true
  tasks: 
    - name: copy jar/war onto tomcat servers
      copy:
        src: /home/amit/opt/playbooks/wabapp/target/webapp.war
	# /home/amit is added in the "firstbranch" new branch
        dest: /opt/apache-tomcat-8.5.41/webapps
